version: "3"
services:
  db:
    container_name: openstarter_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: openstarter
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - openstarter

networks:
  openstarter:
    driver: bridge
